# Version catalog is a central place for you to declare and version dependencies
# https://docs.gradle.org/current/userguide/platforms.html#sub:version-catalog
# https://docs.gradle.org/current/userguide/platforms.html#sub::toml-dependencies-format

[bundles]

kotlinxEcosystem = ["kotlinxDatetime", "kotlinxSerialization", "kotlinxCoroutines"]
kotest = ["kotestRunner", "kotestAssertions", "kotestProperties"]

[plugins]

kotlinPluginSerialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }

[versions]

kotlin = "2.3.0"
kotlinxDatetime = "0.7.1"
kotlinxSerializationJSON = "1.9.0"
kotlinxCoroutines = "1.10.2"
dagger = "2.59"
slf4jApi = "2.0.17"
##    ⬆ = "2.1.0-alpha0"
##    ⬆ = "2.1.0-alpha1"
logbackClassic = "1.5.24"
kotest = "6.1.2"

ksp = "2.3.4"
kotlinPoet = "2.2.0"
autoService = "1.1.1"
autoServiceKsp = "1.2.0"
kotlinCompileTesting = "0.12.1"

[libraries]

kotlinGradlePlugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
kotlinxDatetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinxDatetime" }
kotlinxSerialization = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerializationJSON" }
kotlinxCoroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinxCoroutines" }
slf4jApi = { module = "org.slf4j:slf4j-api", version.ref = "slf4jApi" }
logbackClassic = { module = "ch.qos.logback:logback-classic", version.ref = "logbackClassic" }
daggerCompiler = { module = "com.google.dagger:dagger-compiler", version.ref = "dagger" }
dagger = { module = "com.google.dagger:dagger", version.ref = "dagger" }
kotestRunner = { module = "io.kotest:kotest-runner-junit5", version.ref = "kotest" }
kotestAssertions = { module = "io.kotest:kotest-assertions-core", version.ref = "kotest" }
kotestProperties = { module = "io.kotest:kotest-property", version.ref = "kotest" }

symbolProcessingApi = { module = "com.google.devtools.ksp:symbol-processing-api", version.ref = "ksp" }
kotlinPoet = { module = "com.squareup:kotlinpoet", version.ref = "kotlinPoet" }
kotlinPoetKsp = { module = "com.squareup:kotlinpoet-ksp", version.ref = "kotlinPoet" }

kotlinCompileTestingKsp = { module = "dev.zacsweers.kctfork:ksp", version.ref = "kotlinCompileTesting" }
kotlinCompileTestingCore = { module = "dev.zacsweers.kctfork:core", version.ref = "kotlinCompileTesting" }

autoServiceAnnotations = { module = "com.google.auto.service:auto-service-annotations", version.ref = "autoService" }
autoServiceKsp = { module = "dev.zacsweers.autoservice:auto-service-ksp", version.ref = "autoServiceKsp" }
# Libraries can be bundled together for easier import
